#!/usr/bin/env bash
set -euxo pipefail

python -m pip install --upgrade pip setuptools wheel
# python -m pip install qiskit

# python -m pip install qiskit-aer

# Installiere Jupyter Kernel für Qiskit
python -m ipykernel install --user --name=qiskit --display-name="Python (qiskit)"
